#!/bin/bash
myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;

flag=0

echo

function create_user() {
	useradd -M $uname
	echo "$uname:$pass" | chpasswd
	usermod -e $expdate $uname

	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
	myip2="s/xxxxxxxxx/$myip/g";	
	wget -qO /tmp/client.ovpn "http://vpsaio.ga/Debian7/1194-client.conf"
	sed -i 's/remote xxxxxxxxx 1194/remote xxxxxxxxx 443/g' /tmp/client.ovpn
	sed -i $myip2 /tmp/client.ovpn
	echo ""
	echo "========================="
	echo "Host IP : $myip"
	echo "Port    : 443/22/80"
	echo "Squid   : 8080/3128"
	echo "========================="
	echo "Script by kang Wahid , gunakan akun dengan bijak"
	echo "========================="
}

function renew_user() {
	echo "New expiration date for $uname: $expdate...";
	usermod -e $expdate $uname
}

function delete_user(){
	userdel $uname
}

function expired_users(){
	cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
	totalaccounts=`cat /tmp/expirelist.txt | wc -l`
	for((i=1; i<=$totalaccounts; i++ )); do
		tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
		username=`echo $tuserval | cut -f1 -d:`
		userexp=`echo $tuserval | cut -f2 -d:`
		userexpireinseconds=$(( $userexp * 86400 ))
		todaystime=`date +%s`
		if [ $userexpireinseconds -lt $todaystime ] ; then
			echo $username
		fi
	done
	rm /tmp/expirelist.txt
}

function not_expired_users(){
    cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
    totalaccounts=`cat /tmp/expirelist.txt | wc -l`
    for((i=1; i<=$totalaccounts; i++ )); do
        tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
        username=`echo $tuserval | cut -f1 -d:`
        userexp=`echo $tuserval | cut -f2 -d:`
        userexpireinseconds=$(( $userexp * 86400 ))
        todaystime=`date +%s`
        if [ $userexpireinseconds -gt $todaystime ] ; then
            echo $username
        fi
    done
	rm /tmp/expirelist.txt
}

function used_data(){
	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`
	myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`
	ifconfig $myint | grep "RX bytes" | sed -e 's/ *RX [a-z:0-9]*/Received: /g' | sed -e 's/TX [a-z:0-9]*/\nTransfered: /g'
}

	clear

	echo "--------------- Selamat datang di Server - IP: $myip ---------------"
	echo "Script By      : Ibnu Fachrizal"
	echo "Facebook       : www.facebook.com/ibnufachrizal"
	echo "WA       : 087773091160"
	cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
	cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
	freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
	tram=$( free -m | awk 'NR==2 {print $2}' )
	swap=$( free -m | awk 'NR==4 {print $2}' )
	up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')

	echo -e "\e[032;1mCPU model:\e[0m $cname"
	echo -e "\e[032;1mNumber of cores:\e[0m $cores"
	echo -e "\e[032;1mCPU frequency:\e[0m $freq MHz"
	echo -e "\e[032;1mTotal amount of ram:\e[0m $tram MB"
	echo -e "\e[032;1mTotal amount of swap:\e[0m $swap MB"
	echo -e "\e[032;1mSystem uptime:\e[0m $up"
	echo "------------------------------------------------------------------------------"
	echo "Apa yang ingin Anda lakukan?"
	echo -e "\e[031;1m 1\e[0m) Buat Akun SSH/OpenVPN (\e[34;1muser-add\e[0m)"
	echo -e "\e[031;1m 2\e[0m) Generate Akun Trial (\e[34;1mtrial\e[0m)"
	echo -e "\e[031;1m 3\e[0m) Tambah Masa Aktif Akun SSH/OpenVPN (\e[34;1muser-renew\e[0m)"
	echo -e "\e[031;1m 4\e[0m) Mengubah Password Akun SSH/VPN (\e[34;1mubah-password\e[0m)"
	echo -e "\e[031;1m 5\e[0m) Hapus Akun SSH/OpenVPN (\e[34;1muser-del\e[0m)"
	echo -e "\e[031;1m 6\e[0m) Daftar Akun dan Expire Date (\e[34;1muser-list\e[0m)"
	echo -e "\e[031;1m 7\e[0m) Daftar Akun Aktif (\e[34;1muser-active-list\e[0m)"
	echo -e "\e[031;1m 8\e[0m) Daftar Akun Expire (\e[34;1muser-expire-list\e[0m)"
	echo -e "\e[031;1m 9\e[0m) Delete Akun Expire (\e[34;1mdelete-user-expire\e[0m)"
    echo -e "\e[031;1m10\e[0m) Tendang (\e[34;1mtendang-user-nakal\e[0m)"
    echo -e "\e[031;1m11\e[0m) Speedtest (\e[34;1mcek-speedttes-vps\e[0m)"
	echo -e "\e[031;1m12\e[0m) Monitor User Login (\e[34;1mmonitor-login\e[0m)"
	echo -e "\e[031;1m13\e[0m) Used Data by User (\e[34;1mused-data\e[0m)"
	echo -e "\e[031;1m14\e[0m) Swap Ram (\e[34;1mswap-ram\e[0m)"
	echo -e "\e[031;1m15\e[0m) Memory Usage (\e[34;1mps-mem\e[0m)"
	echo -e "\e[031;1m16\e[0m) Change OpenVPN Port (\e[34;1mchange-openvpn-port\e[0m)"
	echo -e "\e[031;1m17\e[0m) Change Dropbear Port (\e[34;1mchange-dropbear\e[0m)"
	echo -e "\e[031;1m18\e[0m) Change Squid Port (\e[34;1mchange-squid\e[0m)"
	echo -e "\e[031;1m19\e[0m) Restart Dropbear (\e[34;1mrestart-dropbear\e[0m)"
	echo -e "\e[031;1m20\e[0m) Restart OpenVPN (\e[34;1mrestart-openvpn\e[0m)"
	echo -e "\e[031;1m21\e[0m) Restart Webmin (\e[34;1mrestart-webmin\e[0m)"
	echo -e "\e[031;1m22\e[0m) Benchmark (\e[34;1mbenchmark\e[0m)"
	echo -e "\e[031;1m23\e[0m) Ubah Pasword VPS (\e[34;1mpassword\e[0m)"
	echo -e "\e[031;1m24\e[0m) Update Script (\e[34;1mupdate\e[0m)"
	echo -e "\e[031;1m25\e[0m) Reboot Server (\e[34;1mreboot\e[0m)"
	echo -e "\e[031;1m x\e[0m) Exit"
	echo ""
	read -p "Masukkan pilihan anda, kemudian tekan tombol ENTER: " option1
	case $option1 in
        1)
            buatakun
            ;;
        2)	
            trial
			;;	
        3)
            user-list
            #!/bin/bash
            #Script Perpanjang User SSH

            read -p "Username : " Login
            read -p "Password Baru : " Pass
            read -p "Berapa hari akun [$uname] aktif (hari): " masaaktif
            userdel $Login
            useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
            exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
            echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
            echo -e "--------------------------------"

            echo -e "Akun Sudah Diperpanjang Hingga $exp"
            echo -e "Password telah diganti dengan $Pass"
            echo -e "==========================="
            echo -e "Script by \e[1;33;44mIbnu Fachrizal\e[0m"
            ;;	
        4)
			#!/bin/bash
            read -p "Isi Nama Username Yang Akan Diubah Password Nya: " uname
	     	read -p "Silahkan Ditulis Dengan Password Baru: " pass
	    	echo "$uname:$pass" | chpasswd
		    echo "Password Akun SSH/VPN Sudah Diubah Menjadi $pass"
			;;
        5)
            user-list
            read -p "Isikan Username: " uname
            read -p "Apakah Anda benar-benar ingin menghapus akun [$uname] [y/n]: y "
            echo "Akun [$uname] berhasil dihapus!"
            delete_user
            ;;		
		6)
            user-list
            ;;
		7)
			not_expired_users
			;;
		8)
			expired_users
			;;	
		9)
			#!/bin/bash
echo "" > /root/infouser.txt
echo "" > /root/expireduser.txt
echo "" > /home/vps/public_html/status

cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
totalaccounts=`cat /tmp/expirelist.txt | wc -l`
for((i=1; i<=$totalaccounts; i++ ))
       do
       tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
       username=`echo $tuserval | cut -f1 -d:`
       userexp=`echo $tuserval | cut -f2 -d:`
       userexpireinseconds=$(( $userexp * 86400 ))
       tglexp=`date -d @$userexpireinseconds`
       tgl=`echo $tglexp |awk -F" " '{print $3}'`
       while [ ${#tgl} -lt 2 ]
       do
           tgl="0"$tgl
       done
       while [ ${#username} -lt 15 ]
       do
           username=$username" "
       done
       bulantahun=`echo $tglexp |awk -F" " '{print $2,$6}'`
       echo " User : $username Expire tanggal : $tgl $bulantahun" >> /home/vps/public_html/status
       todaystime=`date +%s`
       if [ $userexpireinseconds -ge $todaystime ] ;
           then
           timeto7days=$(( $todaystime + 604800 ))
                if [ $userexpireinseconds -le $timeto7days ];
                then
                     echo " User : $username Expire tanggal : $tgl $bulantahun" >> /root/infouser.txt
                fi
       else
       echo " User : $username Expire tanggal : $tgl $bulantahun" >> /root/expireduser.txt
       userdel $username
       fi
done
echo " "
echo ""
cat /home/vps/public_html/status
echo " "
echo "Semua Akun yang Expired berhasil di matikan !!!"
echo " "
            ;;
        10)	
            echo "Tendang User Nakal"
            tendang
            echo "Tendang User Nakal Done"
			;;
        11)	
            echo "Speed Tes Server"
            ./speedtest.py --share
            echo "Hasil Speed tes diatas Script by Ibnu Fachrizal"
			;;	
        12)
               monssh
	          ;;
		13)
			used_data
			;;
		14)
		    free -h | grep -v + > /tmp/ramcache
            cat /tmp/ramcache | grep -v "Swap"
              ;;
        15)
            /usr/bin/usedram
            ;;
		16)	
            echo "Masukan Port OpenVPN yang diinginkan:"
            read -p "Port: " -e -i 1194 PORT
            sed -i "s/port [0-9]*/port $PORT/" /etc/openvpn/1194.conf
            service openvpn restart
            echo "OpenVPN Updated : Port $PORT"
			;;
		17)	
            echo "Masukan Port Dropbear yang diinginkan:"
            read -p "Port: " -e -i 443 PORT
            sed -i "s/DROPBEAR_PORT=[0-9]*/DROPBEAR_PORT=$PORT/" /etc/default/dropbear
            service dropbear restart
            echo "Dropbear Updated : Port $PORT"
			;;
        18)	
            echo "Masukan Port Squid yang diinginkan:"
            read -p "Port: " -e -i 8080 PORT
            sed -i "s/http_port [0-9]*/http_port $PORT/" /etc/squid3/squid.conf
            service squid3 restart
            echo "echo "Squid3 Updated : Port $PORT""
			;;			
        19)
            echo "Servie dropbear .................tunggu sebentar"
            service dropbear restart
            echo "Restart Dropbear selesai Script by Ibnu Fachrizal"
            ;;
        20)	
            echo "Service Openvpn restart .................tunggu sebentar"
            service openvpn restart
            echo "Restart OpenVPN selesai Script By Ibnu Fachrizal"
			;;	
		21)
		    /etc/init.d/webmin restart
		    echo "Restart Webmin selesai Script By Ibnu Fachrizal"
		    ;;
		22)
            wget freevps.us/downloads/bench.sh -O - -o /dev/null|bash
            ;;
		23)
			passwd
			;;	
		24)
			wget -O debian7 http://vpsaio.ga/Debian7/debian7 && chmod +x debian7 && ./debian7
			;;	
		25)
			reboot
            ;;
        x)
            ;;
        *) menu;;
    esac